# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea3eb3b3270a6f892d10b67826b55ebe0a39db66735d76af73ee8f4dada4c95dc323a93728de4d4eefcad9e71892bdd42ecfb39f9457b0310c4423b1deff37a

test:
  secret_key_base: e145edfc972b1e6ef253988bc2a68cdd49cf69bba2db984ca8161252598fe5f8a7a79c3b05ed5aa0365ca7698e4faf49583b72840a83f5b8284adaba30e7f0a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
